### ISSUE TITLE
Float table headers

### ISSUE THREAD

**Issue by maxrothman** [eepMoody/open5e#104]
On mobile especially, it'd be nice to float the headers of tables until the user fully scrolls past the table.

**Comment by jasonmcalpin** [comment]
you want them to attach to top of screen until they reach bottom of table?

**Comment by maxrothman** [comment]
The user story is "I want to know what each column means when scrolling
through long tables (i.e. class tables) on mobile".

**Comment by jasonmcalpin** [comment]
what about something like this? http://mkoryak.github.io/floatThead/

**Comment by jasonmcalpin** [comment]
there is also something like this: http://jsfiddle.net/jmosbech/stFcx/

**Comment by maxrothman** [comment]
I'd be hesitant to add more scroll areas on mobile, since those can be
really annoying.
