### ISSUE TITLE
Multiple entries with STR of 1

### ISSUE THREAD

**Issue by bigattichouse** [eepMoody/open5e#110]
Again, sorry for not just building a pull request, but I flattened my directory structure.

./mummies/mummy-lord.md:   1 (+4)   | 10 (+0)   | 17 (+3)   | 11 (+0)   | 18 (+4)   | 16 (+3)
./M/merfolk.md:   1 (+0)   | 13 (+1)   | 12 (+1)   | 11 (+0)   | 11 (+0)   | 12 (+1)
./M/medusa.md:   1 (+0)   | 15 (+2)   | 16 (+3)   | 12 (+1)   | 13 (+1)   | 15 (+2)
./S/salamander.md:   1 (+4)   | 14 (+2)   | 15 (+2)   | 11 (+0)   | 10 (+0)   | 12 (+1)
./S/satyr.md:   1 (+1)   | 16 (+3)   | 11 (+0)   | 12 (+1)   | 10 (+0)   | 14 (+2)
./S/specter.md:   1 (-5)   | 14 (+2)   | 11 (+0)   | 10 (+0)   | 10 (+0)   | 11 (+0)
./nagas/spirit-naga.md:   1 (+4)   | 17 (+3)   | 14 (+2)   | 16 (+3)   | 15 (+2)   | 16 (+3)
./nagas/guardian-naga.md:   1 (+4)   | 18 (+4)   | 16 (+3)   | 16 (+3)   | 19 (+4)   | 18 (+4)
./lycanthropes/werebear.md:   1 (+4)   | 10 (+0)   | 17 (+3)   | 11 (+0)   | 12 (+1)   | 12 (+1)
./lycanthropes/werewolf.md:   1 (+2)   | 13 (+1)   | 14 (+2)   | 10 (+0)   | 11 (+0)   | 10 (+0)
./lycanthropes/weretiger.md:   1 (+3)   | 15 (+2)   | 16 (+3)   | 10 (+0)   | 13 (+1)   | 11 (+0)
./O/oni.md:   1 (+4)   | 11 (+0)   | 16 (+3)   | 14 (+2)   | 12 (+1)   | 15 (+2)
./P/pegasus.md:   1 (+4)   | 15 (+2)   | 16 (+3)   | 10 (+0)   | 15 (+2)   | 13 (+1)
./U/unicorn.md:   1 (+4)   | 14 (+2)   | 15 (+2)   | 11 (+0)   | 17 (+3)   | 16 (+3)
./H/half-red-dragon-veteran.md:   1 (+3)   | 13 (+1)   | 14 (+2)   | 10 (+0)   | 11 (+0)   | 10 (+0)
./X/xorn.md:   1 (+3)   | 10 (+0)   | 22 (+6)   | 11 (+0)   | 10 (+0)   | 11 (+0)
./L/lich.md:   1 (+0)   | 16 (+3)   | 16 (+3)   | 20 (+5)   | 14 (+2)   | 16 (+3)
./L/lamia.md:   1 (+3)   | 13 (+1)   | 15 (+2)   | 14 (+2)   | 15 (+2)   | 16 (+3)
./W/will-o-wisp.md:   1 (-5)   | 28 (+9)   | 10 (+0)   | 13 (+1)   | 14 (+2)   | 11 (+0)
./W/wight.md:   1 (+2)   | 14 (+2)   | 16 (+3)   | 10 (+0)   | 13 (+1)   | 15 (+2)
./R/rakshasa.md:   1 (+2)   | 17 (+3)   | 18 (+4)   | 13 (+1)   | 16 (+3)   | 20 (+5)
./hags/night-hag.md:   1 (+4)   | 15 (+2)   | 16 (+3)   | 16 (+3)   | 14 (+2)   | 16 (+3)
./hags/green-hag.md:   1 (+4)   | 12 (+1)   | 16 (+3)   | 13 (+1)   | 14 (+2)   | 14 (+2)
./hags/sea-hag.md:   1 (+3)   | 13 (+1)   | 16 (+3)   | 12 (+1)   | 12 (+1)   | 13 (+1)
./N/nightmare.md:   1 (+4)   | 15 (+2)   | 16 (+3)   | 10 (+0)   | 13 (+1)   | 15 (+2)
./V/vampirespawn.md:   1 (+3)   | 16 (+3)   | 16 (+3)   | 11 (+0)   | 10 (+0)   | 12 (+1)
./V/vampire.md:   1 (+4)   | 18 (+4)   | 18 (+4)   | 17 (+3)   | 15 (+2)   | 18 (+4)
./I/invisible-stalker.md:   1 (+3)   | 19 (+4)   | 14 (+2)   | 10 (+0)   | 15 (+2)   | 11 (+0)

**Comment by jasonmcalpin** [comment]
Stats fixed. Stat block revised in young and hatching dragon gold

**Comment by maxrothman** [comment]
Which PR resolves this issue?

**Comment by jasonmcalpin** [comment]
i did it to master since it was just adding the number back.

**Comment by maxrothman** [comment]
Fixed by https://github.com/eepMoody/open5e/commit/63a9860ff0bba15ea5917a463c9324fb4dd13fab and https://github.com/eepMoody/open5e/commit/65d4fff68754bf7efcdfe489c041b123603af5ff

(Just dropping these here for posterity)
