### ISSUE TITLE
 arrows on mobile. Blackberry

### ISSUE THREAD

**Issue by jasonmcalpin** [eepMoody/open5e#119]

**Comment by maxrothman** [comment]
@jasonmcalpin I have a vague recollection of discovering that this was really just an artifact of hotjar and didn't actually happen for users. Is that correct?

**Comment by maxrothman** [comment]
Ping @jasonmcalpin

**Comment by eepMoody** [comment]
I did some testing and can't replicate this, I think it might have been fixed by HotJar removal.
