### ISSUE TITLE
Google suggests making loading modernizr.min.js nonblocking for performance

### ISSUE THREAD

**Issue by maxrothman** [eepMoody/open5e#154]
Google's performance suggestions pointed out that `https://open5e.com/_static/js/modernizr.min.js` is loading in a blocking manner, and that making it nonblocking would improve performance. Is this feasible? If so, fix it.

**Comment by stuartf** [comment]
It'd be easy to make modernizr load async (non-blocking), but it might actually make things slower, see https://github.com/Modernizr/Modernizr/issues/878
