### ISSUE TITLE
search seems broken

### ISSUE THREAD

**Issue by frankalbenesius** [eepMoody/open5e#185]
I tend to use the search feature a lot. I thought it just got slower recently, but having the console open this time I believe it's just not working at all.

<img width="732" alt="screen shot 2017-01-11 at 10 37 09 am" src="https://cloud.githubusercontent.com/assets/1828900/21857101/f1825ee2-d7e9-11e6-99d8-b6add9b8737c.png">

<img width="467" alt="screen shot 2017-01-11 at 10 34 50 am" src="https://cloud.githubusercontent.com/assets/1828900/21857027/a7d72ab6-d7e9-11e6-8fb6-f261809481e8.png">

<img width="969" alt="screen shot 2017-01-11 at 10 35 29 am" src="https://cloud.githubusercontent.com/assets/1828900/21857042/b0d04f80-d7e9-11e6-9a0f-aa287e35fcdd.png">

Great app, thanks guys.

**Comment by JMMarchant** [comment]
I've been finding this too; looks like a 403 error on moderniser.js.

**Comment by taylregriffin** [comment]
I've also been experiencing this. I just get "Searching..." and never a result.

**Comment by eepMoody** [comment]
Fixed this but forgot to mark it done.
