### ISSUE TITLE
Interest in covering Unearthed Arcana / other offshoot-yet-official content?

### ISSUE THREAD

**Issue by B-Reif** [eepMoody/open5e#187]
I'm presently rolling up an Artificer (via https://media.wizards.com/2016/dnd/downloads/1_UA_Artificer_20170109.pdf). I was wondering about the scope of this project and I'd gladly start working on a pull request for the Artificer if this kind of content fits with open5e.

**Comment by AndruC** [comment]
I'd expect it depends on whether or not Unearthed Arcana's content falls under the OGL.

**Comment by eepMoody** [comment]
@B-Reif currently they are not released under the OGL, so it'd be risking a C&D if we were to add them. I was intending to add them once those things get an official release and an SRD.
