### ISSUE TITLE
Hex missing from (Warlock) spells list

### ISSUE THREAD

**Issue by iisgraveyard** [eepMoody/open5e#215]
The Hex spell is missing from the list of spells. It's described on pg 251 of the PHB (Players Handbook). It is only available on the Warlock spell list as a 1st level spell.

# Hex
_1st-level enchantment_

**Casting Time:** 1 bonus action
**Range:** 90 feet
**Components:** V, S, M (the petrified eye of a newt)
**Duration:** Concentration, up to 1 hour

You place a curse on a creature that you can see within range. Until the spell ends, you deal an extra 1d6 necrotic damage to the target whenever you hit it with an attack. Also, choose one ability when you cast the spell. The target has disadvantage on ability checks made with the chosen ability.
If the target drops to 0 hit points before this spell ends, you can use a bonus action on a subsequent turn of your s to curse a new creature.
A _remove curse_ cast on the target ends this spell early.
**At higher Levels**. When you cast this spell using a spell slot of 3rd or 4th level, you can maintain your concentration on the spell for up to 8 hours. When you use a spell slot of 5th level or higher, you can maintain your concentration on the spell for up to 24 hours.

**Comment by lytedev** [comment]
Hex is not in the SRD and is therefore likely illegal to have on the site.

**Comment by eepMoody** [comment]
As @lytedev mentioned, we can't include it here because it was not included in the SRD. As soon as WoTC publishes a fresh SRD we intend to add it, but until then... :(
