### ISSUE TITLE
Inaccurate table in description for Iron Flask

### ISSUE THREAD

**Issue by ehoogeveen** [eepMoody/open5e#222]
The table in the description for Iron Flask is wrong. The right list is:

    01-50  Empty
    51     Arcanaloth
    52     Cambion
    53-54  Dao
    55-57  Demon (type 1)
    58-60  Demon (type 2)
    61-62  Demon (type 3)
    63-64  Demon (type 4)
    65     Demon (type 5)
    66     Demon (type 6)
    67     Deva
    68-69  Devil (greater)
    70-72  Devil (lesser)
    73-74  Djinni
    75-76  Efreeti
    77-78  Elemental (any)
    79     Githyanki knight
    80     Githzerai zerth
    81-82  Invisible stalker
    83-84  Marid
    85-86  Mezzoloth
    87-88  Night hag
    89-90  Nycaloth
    91     Planetar
    92-93  Salamander
    94-95  Slaad (any)
    96     Solar
    97-98  Succubus/incubus
    99     Ultroloth
    00     Xorn

**Comment by Athaman** [comment]
I think this issue can be closed from my previous commit right?

This is my first open source commit so feel free to let me know if I haven't followed the proper contribution methods.

**Comment by eepMoody** [comment]
@Athaman nope you got it perfectly, I was just in a tough place and wasn't keeping up with issues. Thanks for the help!
