### ISSUE TITLE
Have option to view spells by schools of magic

### ISSUE THREAD

**Issue by bpmcpherson** [eepMoody/open5e#227]
There is already a way to do this based on classes, but having a way to see the different schools would be a useful addition to the site.

**Comment by Taormina** [comment]
@bpmcpherson http://open5e.com/spellcasting/by-school/index.html thoughts?

**Comment by bpmcpherson** [comment]
Looks like the kind of change I was looking for. 

There's an issue with Transmutation cantrips where some code is messing up.

**Comment by Taormina** [comment]
Great catch, fixing now.
