### ISSUE TITLE
How to serve Rules API/Pages/Content?

### ISSUE THREAD

**Issue by eepMoody** [eepMoody/open5e#239]
For our unstructured rules, we need to figure out the best way to serve them up. 

While I'd like to provide them via API, I suspect this will be difficult to structure. The rules don't really have a "shape", just different chapters they belong to.

Could just serve that up by chapter, and serve up sections as an array after them?

```javascript
{'combat': 
  'title': 'Combat',
  'sections': [
  'making-attacks': {
      'title': 'Making Attacks',
      'text': 'markdown text goes here'
    }
  ]
}
```

**Comment by eepMoody** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #239: How to serve Rules API/Pages/Content?](https://trello.com/c/Yx1rm7HK/3-issue-239-how-to-serve-rules-api-pages-content)

**Comment by augustjohnson** [comment]
I opted for this, which is relatively low data. I think that for these large sections, maybe just plain markdown does the trick?  They will never be displayed by themselves (for example, Making Attacks will never need to be referenced off of the Combat page, right?)  So a static blurb is how I opted to do it for these relatively unstructured data types.
```
{
		"name": "Planes",
		"desc": "# Planes\nThe cosmos teems with a multitude of worlds as well as myriad alternate dimensions of reality, called the **planes of.....",
		"parent": "Appendix"
},
```

**Comment by augustjohnson** [comment]
This is probably resolved, I think we've come to a decision at least that content will be generally served like this.

{
            "slug": "poisons",
            "name": "Poisons",
            "desc": "# Poisons\nGiven their insidious and deadly nature, poisons are illegal in most societies but are a favorite tool among assassins, drow, and other evil creatures.\nPoisons come in the following four types.\n**_Contact_**. Contact poison can be smeared on an object and remains potent until it is touched or washed off. A creature that touches contact poison with exposed skin suffers its effects. ... or half as much damage on a successful one.",
            "document_slug": "systems-reference-document"
        },
