### ISSUE TITLE
Compare existing spell list against 5.1 SRD

### ISSUE THREAD

**Issue by eepMoody** [eepMoody/open5e#259]
http://dnd.wizards.com/articles/features/systems-reference-document-srd

**Comment by augustjohnson** [comment]
Just FYI, everything I've been working off of has been the 5.1 document.  I guess technically spells and monsters are the stuff that was there in the .json files, but everything else is straight out of 5.1.

So maybe change this to "Compare existing spell list against 5.1 SRD"
And make a sister issue that's "Compare existing monster list against 5.1 SRD"

**Comment by eepMoody** [comment]
ah, good point! I'll do that.
