### ISSUE TITLE
Compare existing monster list against 5.1 SRD

### ISSUE THREAD

**Issue by eepMoody** [eepMoody/open5e#262]
http://dnd.wizards.com/articles/features/systems-reference-document-srd

**Comment by pj4533** [comment]
I am verifying this data for an app I am currently writing, happy to share my results when I finish.  The common SRD json file floating around the web seems to have several monsters not listed in the actual PDF.  Carrion Crawler being the most obvious, cause it is called out in the intro of the PDF as ‘product identity’.
