### ISSUE TITLE
Put spells and monsters into filterable and sortable tables

### ISSUE THREAD

**Issue by eepMoody** [eepMoody/open5e#264]
Should be filterable and sortable by common attributes like casting time, school, type, duration, etc.

Bonus points: filter and sort by casting class so we don't need to make separate pages for those.

Bonus Bonus: Find a way to get some short summaries in there for the spells.

**Comment by ScottBWar** [comment]
Opened a PR for the monsters table. Same way as the spells.

https://github.com/eepMoody/open5e/pull/293

**Comment by eepMoody** [comment]
This was done by ScottBWar but I forgot to close the issue!
