### ISSUE TITLE
Make custom 404 page

### ISSUE THREAD

**Issue by maxrothman** [eepMoody/open5e#27]
Currently, we serve S3's default 404 page, which is ugly. We'd like a custom 404 page that is:
- funny
- on-brand
- provides an actionable way for users to get moving again, (e.g. link to the home page, highlighting the search)

**Comment by GAZ082** [comment]
I'd like to help with this one, what you need?

**Comment by maxrothman** [comment]
@GAZ082 thanks for offering! I've updated the description with a better definition of what we're looking for. Let me know if you need any help navigating the project.

**Comment by GAZ082** [comment]
So, so a page with a random display of images, dnd related, of course, may get a few from Reddit, and a way to return to the previous page. I just push the HTML/JS and you implement it? There are no bandwidth limits or so?

**Comment by maxrothman** [comment]
If you want to include existent content (header/footer/sidebar/nav/etc.) it'll have to be a Jinja template that gets added via [html_additional_pages](https://github.com/eepMoody/open5e/blob/master/conf.py#L173) ([doc](http://www.sphinx-doc.org/en/stable/config.html#confval-html_additional_pages)).

My instinct is not to include external resources (e.g. reddit) to limit the risk of errors if the external resource is unavailable. Basically, error pages shouldn't break. 

Does that answer your question? I'm sorry I can't give you better design guidance, but the designer on our team is currently on vacation. ¯\_(ツ)_/¯

**Comment by maxrothman** [comment]
Note that to build the html stuff, you'll have to follow the [theme dev setup instructions](https://github.com/eepMoody/open5e/blob/master/README.md#editing-the-theme)
