### ISSUE TITLE
Lots of scrollbars on Firefox MacOS

### ISSUE THREAD

**Issue by augustjohnson** [eepMoody/open5e#305]
Roughly the same scrollbars on Firefox and Safari on MacOS.  Horizontal and two vertical.

<img width="913" alt="Screen Shot 2019-09-16 at 9 19 42 PM" src="https://user-images.githubusercontent.com/827587/65006108-c2373400-d8c7-11e9-97e5-209d501371e4.png">

**Comment by eepMoody** [comment]
@augustjohnson I think this should now be fixed. Can you confirm?

**Comment by eepMoody** [comment]
I believe this is closed, happy to re-open if needed!
