### ISSUE TITLE
monster saves calculated incorrectly

### ISSUE THREAD

**Issue by michaeleconomy** [eepMoody/open5e#307]
https://open5e.com/monsters/adult-black-dragon

observed behavior:
Saving Throws Str + 6, Dex -2, Con + 0, Int + 2, Wis -2, Cha -1

expected behavior:
str +6 Dex    **+7**, Con    **+10**,   int: +2 Wis    **+6**,    Cha    **+8**

The data in the API looks correct, and the non proficient saves look corrects, but the 4 that should be modified  are all wrong.

I expect the problem is in: https://github.com/eepMoody/open5e/blob/master/pages/monsters/_id.vue  line 55

Sorry, i would fix and submit a pull request, but I don't get the .vue format

**Comment by eepMoody** [comment]
Oh, you're absolutely correct! I see what's happening.

I'm passing it into my Stat Bonus calculator component to get the +/- formatting, but I originally just built it to parse out ability scores. It's treating the bonus as a score, and doing too much math.

I'll make a quick update.

**Comment by michaeleconomy** [comment]
Thanks!
