### ISSUE TITLE
Tarrasque

### ISSUE THREAD

**Issue by bigattichouse** [eepMoody/open5e#38]
STR should be 30, not 3 (bonus is correct)

**Comment by bigattichouse** [comment]
Also missing a | between DEX and CON

**Comment by bigattichouse** [comment]
Also Kraken missing strength score.

**Comment by maxrothman** [comment]
Thank you for finding that! I've submitted Pull Request #39 to fix the issues you found. It should be merged and deployed shortly.

**Comment by maxrothman** [comment]
Merged #39
