### ISSUE TITLE
 Standardize monster formatting

### ISSUE THREAD

**Issue by maxrothman** [eepMoody/open5e#86]

**Comment by eepMoody** [comment]
Any specifics here?

**Comment by maxrothman** [comment]
Right now the formatting is pretty raw from the conversion. There are no
headings and it's all over the place. My intention was that someone would
a) think about the design of the monster pages and b) make steps towards
implementing it.

**Comment by jasonmcalpin** [comment]
Is there any other changes to monster layout that are needed?

**Comment by maxrothman** [comment]
Did you make changes?
