### ISSUE TITLE
 Add multicolumn layout to more index pages

### ISSUE THREAD

**Issue by maxrothman** [eepMoody/open5e#98]

**Comment by eepMoody** [comment]
Any suggestions as to which ones?

**Comment by maxrothman** [comment]
The long ones 🙂

Monsters and spells seem like good candidates.

**Comment by eepMoody** [comment]
I think this is done at this point? 

https://open5e.com/Spellcasting/spells_a-z/index.html
https://open5e.com/monsters/index.html
https://open5e.com/monsters/monsters_a-z/index.html

all have it going at this point. https://open5e.com/Spellcasting/index.html only has the spells by letter unless we want to change that and mirror how we did Monsters/index.html?

**Comment by maxrothman** [comment]
I defer to your judgement on Spellcasting/index.html. Otherwise, yes, this looks done.
